### ISSUE TITLE
Settings API

### ISSUE THREAD

**Issue by metatablecat** [metatablecat/Tabby#2]
Provides an interface for accessing Plugin Settings while having easier update APIs

The API would have the following methods:
`Settings:GetSetting()`
`Settings:SetSetting()`
`Settings:GetSettingChangedSignal`
`Settings.SettingChanged`
`Settings.UpdateSetting`

Design is needed for this.

**Comment by metatablecat** [comment]
I want to approach this differently, maybe with a strictly typed SettingHost object that makes it easier to explicity typecheck your settings. This might however, unintentionally create a new folder in a Tabby project

**Comment by ItsOndrik** [comment]
Settings.debugMode = nil
Settings.debugMode = true

local event = Settings:GetSettingChangedSignal("debugMode")

**Comment by metatablecat** [comment]
Implemented.
